name: ReegoMC
version: ${project.version}
main: org.reego.reegomc.ReegoMC
authors: [ JAYJAYTEE ]
commands:
  build:
  reloadEconomy:
    aliases:
      - saveeco
      - reloadeco
      - saveeconomy
  coins:
    aliases:
      - coin
      - cash
      - money
      - bal
      - balance